/**
 * Display different letters
 */

#include <Arduino.h>
#include "Digispark_Charlieplex.h"

#define LED_DELAY 1

void FORKYOUR_LEDon_MF(int vin, int gnd)
{
  pinMode(0, INPUT);
  pinMode(1, INPUT);
  pinMode(2, INPUT);
  pinMode(3, INPUT);
  pinMode(4, INPUT);
  pinMode(5, INPUT);
  
  pinMode(vin, OUTPUT);
  pinMode(gnd, OUTPUT);
  
  digitalWrite(vin, HIGH);
  digitalWrite(gnd, LOW);
  
  delay(LED_DELAY);
}

void FORKYOUR_allOn_MF()
{
  FORKYOUR_LEDon_MF(0, 1);
  FORKYOUR_LEDon_MF(0, 2);
  FORKYOUR_LEDon_MF(0, 3);
  FORKYOUR_LEDon_MF(0, 4);
  FORKYOUR_LEDon_MF(1, 0);
  FORKYOUR_LEDon_MF(1, 2);
  FORKYOUR_LEDon_MF(1, 3);
  FORKYOUR_LEDon_MF(1, 4);
  FORKYOUR_LEDon_MF(2, 0);
  FORKYOUR_LEDon_MF(2, 1);
  FORKYOUR_LEDon_MF(2, 3);
  FORKYOUR_LEDon_MF(2, 4);
  FORKYOUR_LEDon_MF(3, 0);
  FORKYOUR_LEDon_MF(3, 1);
  FORKYOUR_LEDon_MF(3, 2);
  FORKYOUR_LEDon_MF(3, 4);
  FORKYOUR_LEDon_MF(4, 0);
  FORKYOUR_LEDon_MF(4, 1);
  FORKYOUR_LEDon_MF(4, 2);
  FORKYOUR_LEDon_MF(4, 3);
}

void FORKYOUR_showA_MF()
{
  FORKYOUR_LEDon_MF(0, 1);
  FORKYOUR_LEDon_MF(0, 4);
  FORKYOUR_LEDon_MF(1, 0);
  FORKYOUR_LEDon_MF(1, 4);
  FORKYOUR_LEDon_MF(2, 0);
  FORKYOUR_LEDon_MF(2, 1);
  FORKYOUR_LEDon_MF(2, 3);
  FORKYOUR_LEDon_MF(2, 4);
  FORKYOUR_LEDon_MF(3, 0);
  FORKYOUR_LEDon_MF(3, 4);
  FORKYOUR_LEDon_MF(4, 1);
  FORKYOUR_LEDon_MF(4, 2);
}

void FORKYOUR_showB_MF()
{
  FORKYOUR_LEDon_MF(0, 1);
  FORKYOUR_LEDon_MF(0, 2);
  FORKYOUR_LEDon_MF(0, 3);
  FORKYOUR_LEDon_MF(1, 0);
  FORKYOUR_LEDon_MF(1, 4);
  FORKYOUR_LEDon_MF(2, 0);
  FORKYOUR_LEDon_MF(2, 1);
  FORKYOUR_LEDon_MF(2, 3);
  FORKYOUR_LEDon_MF(3, 0);
  FORKYOUR_LEDon_MF(3, 4);
  FORKYOUR_LEDon_MF(4, 0);
  FORKYOUR_LEDon_MF(4, 1);
  FORKYOUR_LEDon_MF(4, 2);
}

void FORKYOUR_showC_MF()
{
  FORKYOUR_LEDon_MF(0, 2);
  FORKYOUR_LEDon_MF(0, 3);
  FORKYOUR_LEDon_MF(1, 0);
  FORKYOUR_LEDon_MF(1, 4);
  FORKYOUR_LEDon_MF(2, 0);
  FORKYOUR_LEDon_MF(3, 0);
  FORKYOUR_LEDon_MF(3, 4);
  FORKYOUR_LEDon_MF(4, 1);
  FORKYOUR_LEDon_MF(4, 2);
}

void FORKYOUR_showD_MF()
{
  FORKYOUR_LEDon_MF(0, 1);
  FORKYOUR_LEDon_MF(0, 2);
  FORKYOUR_LEDon_MF(0, 3);
  FORKYOUR_LEDon_MF(1, 0);
  FORKYOUR_LEDon_MF(1, 4);
  FORKYOUR_LEDon_MF(2, 0);
  FORKYOUR_LEDon_MF(2, 4);
  FORKYOUR_LEDon_MF(3, 0);
  FORKYOUR_LEDon_MF(3, 4);
  FORKYOUR_LEDon_MF(4, 0);
  FORKYOUR_LEDon_MF(4, 1);
  FORKYOUR_LEDon_MF(4, 2); 
}

void FORKYOUR_showE_MF()
{
  FORKYOUR_LEDon_MF(0, 1);
  FORKYOUR_LEDon_MF(0, 2);
  FORKYOUR_LEDon_MF(0, 3);
  FORKYOUR_LEDon_MF(0, 4);
  FORKYOUR_LEDon_MF(1, 0);
  FORKYOUR_LEDon_MF(2, 0);
  FORKYOUR_LEDon_MF(2, 1);
  FORKYOUR_LEDon_MF(2, 3);
  FORKYOUR_LEDon_MF(3, 0);
  FORKYOUR_LEDon_MF(4, 0);
  FORKYOUR_LEDon_MF(4, 1);
  FORKYOUR_LEDon_MF(4, 2);
  FORKYOUR_LEDon_MF(4, 3);
}

void FORKYOUR_showF_MF()
{
  FORKYOUR_LEDon_MF(0, 1);
  FORKYOUR_LEDon_MF(1, 0);
  FORKYOUR_LEDon_MF(2, 0);
  FORKYOUR_LEDon_MF(2, 1);
  FORKYOUR_LEDon_MF(2, 3);
  FORKYOUR_LEDon_MF(3, 0);
  FORKYOUR_LEDon_MF(4, 0);
  FORKYOUR_LEDon_MF(4, 1);
  FORKYOUR_LEDon_MF(4, 2);
  FORKYOUR_LEDon_MF(4, 3);
}

void FORKYOUR_showG_MF()
{
  FORKYOUR_LEDon_MF(0, 2);
  FORKYOUR_LEDon_MF(0, 3);
  FORKYOUR_LEDon_MF(1, 0);
  FORKYOUR_LEDon_MF(1, 4);
  FORKYOUR_LEDon_MF(2, 0);
  FORKYOUR_LEDon_MF(2, 3);
  FORKYOUR_LEDon_MF(2, 4);
  FORKYOUR_LEDon_MF(3, 0);
  FORKYOUR_LEDon_MF(4, 1);
  FORKYOUR_LEDon_MF(4, 2);
  FORKYOUR_LEDon_MF(4, 3);
}

void FORKYOUR_showH_MF()
{
  FORKYOUR_LEDon_MF(0, 1);
  FORKYOUR_LEDon_MF(0, 4);
  FORKYOUR_LEDon_MF(1, 0);
  FORKYOUR_LEDon_MF(1, 4);
  FORKYOUR_LEDon_MF(2, 0);
  FORKYOUR_LEDon_MF(2, 1);
  FORKYOUR_LEDon_MF(2, 3);
  FORKYOUR_LEDon_MF(2, 4);
  FORKYOUR_LEDon_MF(3, 0);
  FORKYOUR_LEDon_MF(3, 4);
  FORKYOUR_LEDon_MF(4, 0);
  FORKYOUR_LEDon_MF(4, 3);
}

void FORKYOUR_showI_MF()
{
  FORKYOUR_LEDon_MF(0, 1);
  FORKYOUR_LEDon_MF(0, 2);
  FORKYOUR_LEDon_MF(0, 3);
  FORKYOUR_LEDon_MF(0, 4);
  FORKYOUR_LEDon_MF(1, 2);
  FORKYOUR_LEDon_MF(1, 3);
  FORKYOUR_LEDon_MF(2, 1);
  FORKYOUR_LEDon_MF(2, 3);
  FORKYOUR_LEDon_MF(3, 1);
  FORKYOUR_LEDon_MF(3, 2);
  FORKYOUR_LEDon_MF(4, 0);
  FORKYOUR_LEDon_MF(4, 1);
  FORKYOUR_LEDon_MF(4, 2);
  FORKYOUR_LEDon_MF(4, 3);
}

void FORKYOUR_showJ_MF()
{
  FORKYOUR_LEDon_MF(0, 2);
  FORKYOUR_LEDon_MF(0, 3);
  FORKYOUR_LEDon_MF(1, 0);
  FORKYOUR_LEDon_MF(1, 4);
  FORKYOUR_LEDon_MF(2, 4);
  FORKYOUR_LEDon_MF(3, 4);
  FORKYOUR_LEDon_MF(4, 3);
}

void FORKYOUR_showK_MF()
{
  FORKYOUR_LEDon_MF(0, 1);
  FORKYOUR_LEDon_MF(0, 4);
  FORKYOUR_LEDon_MF(1, 0);
  FORKYOUR_LEDon_MF(1, 3);
  FORKYOUR_LEDon_MF(2, 0);
  FORKYOUR_LEDon_MF(2, 1);
  FORKYOUR_LEDon_MF(3, 0);
  FORKYOUR_LEDon_MF(3, 2);
  FORKYOUR_LEDon_MF(4, 0);
  FORKYOUR_LEDon_MF(4, 3);
}

void FORKYOUR_showL_MF()
{
  FORKYOUR_LEDon_MF(0, 1);
  FORKYOUR_LEDon_MF(0, 2);
  FORKYOUR_LEDon_MF(0, 3);
  FORKYOUR_LEDon_MF(0, 4);
  FORKYOUR_LEDon_MF(1, 0);
  FORKYOUR_LEDon_MF(2, 0);
  FORKYOUR_LEDon_MF(3, 0);
  FORKYOUR_LEDon_MF(4, 0);
}

void FORKYOUR_showM_MF()
{
  FORKYOUR_LEDon_MF(0, 1);
  FORKYOUR_LEDon_MF(0, 4);
  FORKYOUR_LEDon_MF(1, 0);
  FORKYOUR_LEDon_MF(1, 4);
  FORKYOUR_LEDon_MF(2, 0);
  FORKYOUR_LEDon_MF(2, 4);
  FORKYOUR_LEDon_MF(3, 0);
  FORKYOUR_LEDon_MF(3, 1);
  FORKYOUR_LEDon_MF(3, 2);
  FORKYOUR_LEDon_MF(3, 4);
  FORKYOUR_LEDon_MF(4, 0);
  FORKYOUR_LEDon_MF(4, 3);
}

void FORKYOUR_showN_MF()
{
  FORKYOUR_LEDon_MF(0, 1);
  FORKYOUR_LEDon_MF(0, 4);
  FORKYOUR_LEDon_MF(1, 0);
  FORKYOUR_LEDon_MF(1, 3);
  FORKYOUR_LEDon_MF(1, 4);
  FORKYOUR_LEDon_MF(2, 0);
  FORKYOUR_LEDon_MF(2, 3);
  FORKYOUR_LEDon_MF(2, 4);
  FORKYOUR_LEDon_MF(3, 0);
  FORKYOUR_LEDon_MF(3, 1);
  FORKYOUR_LEDon_MF(3, 4);
  FORKYOUR_LEDon_MF(4, 0);
  FORKYOUR_LEDon_MF(4, 3);
}

void FORKYOUR_showO_MF()
{
  FORKYOUR_LEDon_MF(0, 2);
  FORKYOUR_LEDon_MF(0, 3);
  FORKYOUR_LEDon_MF(1, 0);
  FORKYOUR_LEDon_MF(1, 4);
  FORKYOUR_LEDon_MF(2, 0);
  FORKYOUR_LEDon_MF(2, 4);
  FORKYOUR_LEDon_MF(3, 0);
  FORKYOUR_LEDon_MF(3, 4);
  FORKYOUR_LEDon_MF(4, 1);
  FORKYOUR_LEDon_MF(4, 2);
}

void FORKYOUR_showP_MF()
{
  FORKYOUR_LEDon_MF(0, 1);
  FORKYOUR_LEDon_MF(1, 0);
  FORKYOUR_LEDon_MF(2, 0);
  FORKYOUR_LEDon_MF(2, 1);
  FORKYOUR_LEDon_MF(2, 3);
  FORKYOUR_LEDon_MF(3, 0);
  FORKYOUR_LEDon_MF(3, 4);
  FORKYOUR_LEDon_MF(4, 0);
  FORKYOUR_LEDon_MF(4, 1);
  FORKYOUR_LEDon_MF(4, 2);
}

void FORKYOUR_showQ_MF()
{
  FORKYOUR_LEDon_MF(0, 2);
  FORKYOUR_LEDon_MF(0, 3);
  FORKYOUR_LEDon_MF(0, 4);
  FORKYOUR_LEDon_MF(1, 0);
  FORKYOUR_LEDon_MF(1, 3);
  FORKYOUR_LEDon_MF(1, 4);
  FORKYOUR_LEDon_MF(2, 0);
  FORKYOUR_LEDon_MF(2, 4);
  FORKYOUR_LEDon_MF(3, 0);
  FORKYOUR_LEDon_MF(3, 4);
  FORKYOUR_LEDon_MF(4, 1);
  FORKYOUR_LEDon_MF(4, 2);
}

void FORKYOUR_showR_MF()
{
  FORKYOUR_LEDon_MF(0, 1);
  FORKYOUR_LEDon_MF(0, 4);
  FORKYOUR_LEDon_MF(1, 0);
  FORKYOUR_LEDon_MF(1, 3);
  FORKYOUR_LEDon_MF(2, 0);
  FORKYOUR_LEDon_MF(2, 1);
  FORKYOUR_LEDon_MF(2, 3);
  FORKYOUR_LEDon_MF(3, 0);
  FORKYOUR_LEDon_MF(3, 4);
  FORKYOUR_LEDon_MF(4, 0);
  FORKYOUR_LEDon_MF(4, 1);
  FORKYOUR_LEDon_MF(4, 2);
}

void FORKYOUR_showS_MF()
{
  FORKYOUR_LEDon_MF(0, 1);
  FORKYOUR_LEDon_MF(0, 2);
  FORKYOUR_LEDon_MF(0, 3);
  FORKYOUR_LEDon_MF(1, 4);
  FORKYOUR_LEDon_MF(2, 1);
  FORKYOUR_LEDon_MF(2, 3);
  FORKYOUR_LEDon_MF(3, 0);
  FORKYOUR_LEDon_MF(4, 1);
  FORKYOUR_LEDon_MF(4, 2);
  FORKYOUR_LEDon_MF(4, 3);
}

void FORKYOUR_showT_MF()
{
  FORKYOUR_LEDon_MF(0, 2);
  FORKYOUR_LEDon_MF(0, 3);
  FORKYOUR_LEDon_MF(1, 2);
  FORKYOUR_LEDon_MF(1, 3);
  FORKYOUR_LEDon_MF(2, 1);
  FORKYOUR_LEDon_MF(2, 3);
  FORKYOUR_LEDon_MF(3, 1);
  FORKYOUR_LEDon_MF(3, 2);
  FORKYOUR_LEDon_MF(4, 0);
  FORKYOUR_LEDon_MF(4, 1);
  FORKYOUR_LEDon_MF(4, 2);
  FORKYOUR_LEDon_MF(4, 3);
}

void FORKYOUR_showU_MF()
{
  FORKYOUR_LEDon_MF(0, 2);
  FORKYOUR_LEDon_MF(0, 3);
  FORKYOUR_LEDon_MF(1, 0);
  FORKYOUR_LEDon_MF(1, 4);
  FORKYOUR_LEDon_MF(2, 0);
  FORKYOUR_LEDon_MF(2, 4);
  FORKYOUR_LEDon_MF(3, 0);
  FORKYOUR_LEDon_MF(3, 4);
  FORKYOUR_LEDon_MF(4, 0);
  FORKYOUR_LEDon_MF(4, 3);
}

void FORKYOUR_showV_MF()
{
  FORKYOUR_LEDon_MF(0, 2);
  FORKYOUR_LEDon_MF(1, 0);
  FORKYOUR_LEDon_MF(1, 3);
  FORKYOUR_LEDon_MF(2, 0);
  FORKYOUR_LEDon_MF(2, 4);
  FORKYOUR_LEDon_MF(3, 0);
  FORKYOUR_LEDon_MF(3, 4);
  FORKYOUR_LEDon_MF(4, 0);
  FORKYOUR_LEDon_MF(4, 3);
}

void FORKYOUR_showW_MF()
{
  FORKYOUR_LEDon_MF(0, 1);
  FORKYOUR_LEDon_MF(0, 4);
  FORKYOUR_LEDon_MF(1, 0);
  FORKYOUR_LEDon_MF(1, 2);
  FORKYOUR_LEDon_MF(1, 3);
  FORKYOUR_LEDon_MF(1, 4);
  FORKYOUR_LEDon_MF(2, 0);
  FORKYOUR_LEDon_MF(2, 4);
  FORKYOUR_LEDon_MF(3, 0);
  FORKYOUR_LEDon_MF(3, 4);
  FORKYOUR_LEDon_MF(4, 0);
  FORKYOUR_LEDon_MF(4, 3);
}

void FORKYOUR_showX_MF()
{
  FORKYOUR_LEDon_MF(0, 1);
  FORKYOUR_LEDon_MF(0, 4);
  FORKYOUR_LEDon_MF(1, 0);
  FORKYOUR_LEDon_MF(1, 4);
  FORKYOUR_LEDon_MF(2, 1);
  FORKYOUR_LEDon_MF(2, 3);
  FORKYOUR_LEDon_MF(3, 0);
  FORKYOUR_LEDon_MF(3, 4);
  FORKYOUR_LEDon_MF(4, 0);
  FORKYOUR_LEDon_MF(4, 3);
}

void FORKYOUR_showY_MF()
{
  FORKYOUR_LEDon_MF(0, 2);
  FORKYOUR_LEDon_MF(0, 3);
  FORKYOUR_LEDon_MF(1, 2);
  FORKYOUR_LEDon_MF(1, 3);
  FORKYOUR_LEDon_MF(2, 1);
  FORKYOUR_LEDon_MF(2, 3);
  FORKYOUR_LEDon_MF(3, 0);
  FORKYOUR_LEDon_MF(3, 4);
  FORKYOUR_LEDon_MF(4, 0);
  FORKYOUR_LEDon_MF(4, 3);
}

void FORKYOUR_showZ_MF()
{
  FORKYOUR_LEDon_MF(0, 1);
  FORKYOUR_LEDon_MF(0, 2);
  FORKYOUR_LEDon_MF(0, 3);
  FORKYOUR_LEDon_MF(0, 4);
  FORKYOUR_LEDon_MF(1, 2);
  FORKYOUR_LEDon_MF(2, 3);
  FORKYOUR_LEDon_MF(3, 4);
  FORKYOUR_LEDon_MF(4, 0);
  FORKYOUR_LEDon_MF(4, 1);
  FORKYOUR_LEDon_MF(4, 2);
  FORKYOUR_LEDon_MF(4, 3);
}
